package com.snatik.matches.ui.character

import android.content.res.AssetManager
import android.graphics.Path
import android.graphics.RectF
import androidx.core.graphics.PathParser
import androidx.core.graphics.toColorInt

/**
 * A card character as vector paths, loaded from assets/characters/<name>.chr, generated by the
 * CharacterTracer in tools/. Each path is tagged with the part it belongs to (body, eye, pupil,
 * shadow) so the drawable can move parts independently.
 */
class Character(
    val width: Float,
    val height: Float,
    val parts: List<Part>,
) {
    enum class Group { BODY, EYE, PUPIL, SHADOW }

    class Part(val group: Group, val color: Int, val path: Path) {
        val bounds = RectF().also { path.computeBounds(it, true) }
        val area: Float get() = bounds.width() * bounds.height()
    }

    val hasEyes: Boolean get() = parts.any { it.group == Group.EYE || it.group == Group.PUPIL }

    companion object {
        fun load(assets: AssetManager, name: String): Character? {
            val text = runCatching { assets.open("characters/$name.chr").bufferedReader().readText() }.getOrNull() ?: return null
            val lines = text.lineSequence().filter { it.isNotBlank() }.iterator()
            val (w, h) = lines.next().split(' ').map { it.toFloat() }
            val parts = lines.asSequence().map { line ->
                val group = line.substringBefore(' ')
                val rest = line.substringAfter(' ')
                val color = rest.substringBefore(' ')
                val data = rest.substringAfter(' ')
                Part(Group.valueOf(group.uppercase()), color.toColorInt(), PathParser.createPathFromPathData(data))
            }.toList()
            return Character(w, h, parts)
        }
    }
}
